version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: mchagass/agendamento-odontologico:sprint4
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: odonto_postgres_data

networks:
  app-network:
    driver: bridge 